title:             Memory.sh 博客
email:             zysh@mail.ustc.edu.cn
description:       一只小白~坚持每天写~
author:            memory.sh
baseurl:           ""
url:               "http://shenzhengyang.github.io"

# Social Profiles
github_username:   shenzhengyang

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
